spring:
  datasource:
    url: jdbc:postgresql://${PGHOST}:/${PGPORT}/${PDDATABASE}
    username: ${PGUSER}
    password: ${PGPASSWORD}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create


spring:
  datasource:
    url: jdbc:h2:mem:sbj2023
    username: sbj2023
    password:
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: create # validate | update | create | create-drop
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false
